
export const resources = [
  {
    id: 1,
    title: "Introduction to HTML and CSS",
    description: "Learn the fundamentals of web development with this comprehensive beginner's guide to HTML and CSS.",
    category: "Programming",
    tags: ["HTML", "CSS", "Web Development", "Frontend"],
    difficulty: "beginner" as const,
    duration: "2-3 hours",
    rating: 4.7,
    provider: "MDN Web Docs",
    url: "https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web",
  },
  {
    id: 2,
    title: "JavaScript Algorithms and Data Structures",
    description: "Master common algorithms and data structures with JavaScript. Perfect for interview preparation.",
    category: "Programming",
    tags: ["JavaScript", "Algorithms", "Data Structures", "Computer Science"],
    difficulty: "intermediate" as const,
    duration: "20-30 hours",
    rating: 4.9,
    provider: "freeCodeCamp",
    url: "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/",
  },
  {
    id: 3,
    title: "Machine Learning Crash Course",
    description: "A fast-paced, practical introduction to machine learning fundamentals using TensorFlow.",
    category: "Data Science",
    tags: ["Machine Learning", "TensorFlow", "AI", "Python"],
    difficulty: "intermediate" as const,
    duration: "15 hours",
    rating: 4.6,
    provider: "Google",
    url: "https://developers.google.com/machine-learning/crash-course",
  },
  {
    id: 4,
    title: "UI/UX Design Fundamentals",
    description: "Learn the core principles of user interface and user experience design through practical examples.",
    category: "Design",
    tags: ["UI", "UX", "Design", "User Research"],
    difficulty: "beginner" as const,
    duration: "8-10 hours",
    rating: 4.3,
    provider: "Interaction Design Foundation",
    url: "https://www.interaction-design.org/courses",
  },
  {
    id: 5,
    title: "Advanced React Patterns",
    description: "Discover advanced React patterns and techniques to build scalable and maintainable applications.",
    category: "Programming",
    tags: ["React", "JavaScript", "Frontend", "Web Development"],
    difficulty: "advanced" as const,
    duration: "6-8 hours",
    rating: 4.8,
    provider: "Kent C. Dodds",
    url: "https://kentcdodds.com/blog/advanced-react-patterns",
  },
  {
    id: 6,
    title: "Introduction to Data Science with Python",
    description: "Get started with data science using Python, NumPy, pandas, and matplotlib.",
    category: "Data Science",
    tags: ["Python", "Data Science", "Data Analysis", "Statistics"],
    difficulty: "beginner" as const,
    duration: "12-15 hours",
    rating: 4.5,
    provider: "DataCamp",
    url: "https://www.datacamp.com/courses/intro-to-python-for-data-science",
  },
  {
    id: 7,
    title: "Responsive Web Design",
    description: "Learn how to make websites that respond to different screen sizes and devices.",
    category: "Programming",
    tags: ["CSS", "HTML", "Web Development", "Responsive Design"],
    difficulty: "beginner" as const,
    duration: "15-20 hours",
    rating: 4.4,
    provider: "freeCodeCamp",
    url: "https://www.freecodecamp.org/learn/responsive-web-design/",
  },
  {
    id: 8,
    title: "Graphic Design Principles",
    description: "Understand the fundamental principles of graphic design and visual communication.",
    category: "Design",
    tags: ["Graphic Design", "Typography", "Color Theory", "Layout"],
    difficulty: "beginner" as const,
    duration: "10 hours",
    rating: 4.2,
    provider: "Canva Design School",
    url: "https://www.canva.com/learn/design/",
  },
  {
    id: 9,
    title: "Deep Learning Specialization",
    description: "Master deep learning concepts and techniques through hands-on projects and assignments.",
    category: "Data Science",
    tags: ["Deep Learning", "Neural Networks", "AI", "Python"],
    difficulty: "advanced" as const,
    duration: "40-50 hours",
    rating: 4.9,
    provider: "Coursera (Andrew Ng)",
    url: "https://www.coursera.org/specializations/deep-learning",
  },
  {
    id: 10,
    title: "Linear Algebra for Machine Learning",
    description: "Learn the essential linear algebra concepts needed for machine learning and data science.",
    category: "Mathematics",
    tags: ["Linear Algebra", "Mathematics", "Machine Learning", "Vectors"],
    difficulty: "intermediate" as const,
    duration: "12 hours",
    rating: 4.7,
    provider: "3Blue1Brown",
    url: "https://www.3blue1brown.com/topics/linear-algebra",
  },
  {
    id: 11,
    title: "Docker for Beginners",
    description: "Get started with Docker and containerization for modern application development.",
    category: "Programming",
    tags: ["Docker", "Containers", "DevOps", "Deployment"],
    difficulty: "beginner" as const,
    duration: "6 hours",
    rating: 4.4,
    provider: "Docker Documentation",
    url: "https://docs.docker.com/get-started/",
  },
  {
    id: 12,
    title: "Product Management Fundamentals",
    description: "Learn the core principles and practices of effective product management.",
    category: "Business",
    tags: ["Product Management", "Business", "Strategy", "User Stories"],
    difficulty: "intermediate" as const,
    duration: "10-12 hours",
    rating: 4.3,
    provider: "Product School",
    url: "https://www.productschool.com/blog/",
  },
  {
    id: 13,
    title: "Game Development with Unity",
    description: "Build your first game using the Unity game engine and C# programming.",
    category: "Programming",
    tags: ["Unity", "Game Development", "C#", "3D"],
    difficulty: "intermediate" as const,
    duration: "25 hours",
    rating: 4.6,
    provider: "Unity Learn",
    url: "https://learn.unity.com/",
  },
  {
    id: 14,
    title: "Introduction to Psychology",
    description: "Explore the fundamental concepts and theories in modern psychology.",
    category: "Science",
    tags: ["Psychology", "Social Science", "Behavior", "Mind"],
    difficulty: "beginner" as const,
    duration: "15 hours",
    rating: 4.5,
    provider: "Khan Academy",
    url: "https://www.khanacademy.org/science/health-and-medicine/mental-health",
  },
  {
    id: 15,
    title: "Spanish for Beginners",
    description: "Learn basic Spanish vocabulary, grammar, and conversation skills.",
    category: "Language",
    tags: ["Spanish", "Language Learning", "Grammar", "Vocabulary"],
    difficulty: "beginner" as const,
    duration: "30 hours",
    rating: 4.2,
    provider: "Duolingo",
    url: "https://www.duolingo.com/course/es/en/Learn-Spanish",
  }
];
