// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://paarduehupvrshjnpyhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhYXJkdWVodXB2cnNoam5weWhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjU5MTcsImV4cCI6MjA2NTE0MTkxN30.g7PhctaBXVBLKxRmhB8ab51RU_PBec5fmFEKPzXPTK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);